name: Build Windows Setup

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set Version
        shell: pwsh
        run: |
          $package = Get-Content package.json -Raw | ConvertFrom-Json

          $package.version = "1.0.1"

          $package | ConvertTo-Json -Depth 100 | Set-Content package.json -Encoding UTF8

          Write-Host "Windows version set to 1.0.1"

      - name: Install dependencies
        run: npm install

      - name: Install Electron & Builder
        run: |
          npm install electron@^38.0.0 electron-builder@^26.0.0

      - name: Build Windows Installer
        run: |
          npm run build-windows-installer

      - name: List Build Output
        shell: pwsh
        run: |
          Write-Host "===== WINDOWS BUILD OUTPUT ====="
          Get-ChildItem -Path dist -Recurse
          Write-Host "================================"

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: TEXFOREVER-Windows-Setup
          path: dist/*.exe
          if-no-files-found: error
